function mycallback(r)  %r here is the RemoteControl object
  if r.isInit()
    %Initialize the set of runs. This stage is only called once.
    %Use it to specify the values of the parameter you want to change
    %and the number of runs to take

    r.data.param = (1:1:10)*10^-3;


  elseif r.isSet()
    %This is called at the start of every run of the experiment.
    %Use it to create a new sequence to upload based on the current
    %parameter, and upload that sequence.  Do not use the r.run()
    %method here!
  elseif r.isAnalyze()
    %This is called after the LabVIEW control program is finished
    %Use it to analyze data generated by the experiment
    %You can store processed data in the experiment as fields in 
    %the property r.data
  end
end